export const BaseURL = 'https://api.openweathermap.org/data/2.5/';
export const key = 'aa2e6dec90a2a06507400ecaa5e24d1c';

export const LOADING_DAILY_WEATHER_DATA = 'LOADING_DAILY_WEATHER_DATA';
export const GET_DAILY_WEATHER_DATA = 'GET_DAILY_WEATHER_DATA';
export const ERROR_DAILY_WEATHER_DATA = 'ERROR_DAILY_WEATHER_DATA';

export const LOADING_CURRENT_WEATHER_DATA = 'LOADING_CURRENT_WEATHER_DATA';
export const GET_CURRENT_WEATHER_DATA = 'GET_CURRENT_WEATHER_DATA';
export const ERROR_CURRENT_WEATHER_DATA = 'ERROR_CURRENT_WEATHER_DATA';
